#Build Stage
FROM python:3.12-alpine AS build

COPY requirements.txt .

RUN pip install --no-cache-dir --no-compile --target=/install -r requirements.txt

#Production Stage
FROM python:3.12-alpine AS production

COPY --from=build /install /usr/local/lib/python3.12/site-packages

WORKDIR /orchestrator

COPY . .

CMD ["python", "orch.py"]
