apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: default
type: Opaque
data:
  REACT_APP_BACKEND_URL: aHR0cDovLzE5NC4xNzEuMjAyLjIzMC9hcGk=
  BACKEND_PORT: ODA4MA==
  ORY_KRATOS_ADMIN_PORT: NDQzMw==
  ORY_KRATOS_PUBLIC_PORT: NDQzNA==
