spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${BACKEND_PORT}

## RabbitMQ Configuration ##
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}

## MinIO Configuration ##
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

## Cassandra Configuration ##
spring.data.cassandra.host=${CASSANDRA_HOST}
spring.data.cassandra.port=${CASSANDRA_PORT}
spring.data.cassandra.username=${CASSANDRA_USERNAME}
spring.data.cassandra.password=${CASSANDRA_PASSWORD}

## Ory Configuration ##
ory.keto.url=${KETO_URL}
ory.keto.port=${KETO_PORT}
ory.kratos.url=${KRATOS_URL}
ory.kratos.port=${KRATOS_PUBLIC_PORT}

# Master IP for Cors
master.ip=${MASTER_IP}